import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import {
  ArrowRight,
  FileText,
  Bot,
  HardHat,
  ShieldCheck,
  UploadCloud,
  FileSearch,
  Wand2,
  Scissors,
  Cpu,
  Database,
  Search,
  CheckCircle2,
  LayoutDashboard,
  KeyRound,
  Users,
} from "lucide-react";

function useInView() {
  const ref = useRef(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setVisible(true);
          obs.disconnect();
        }
      },
      { threshold: 0.15 }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return [ref, visible];
}

const VARIANTS = {
  up: "translate-y-6 opacity-0",
  left: "-translate-x-6 opacity-0",
  right: "translate-x-6 opacity-0",
  scale: "scale-95 opacity-0",
};

function Reveal({ children, variant = "up", delay = 0, className = "" }) {
  const [ref, visible] = useInView();
  return (
    <div
      ref={ref}
      style={{ transitionDelay: visible ? `${delay}ms` : "0ms" }}
      className={`transition-all duration-700 ease-out ${
        visible ? "translate-x-0 translate-y-0 scale-100 opacity-100" : VARIANTS[variant]
      } ${className}`}
    >
      {children}
    </div>
  );
}

// ---------- data ----------
const PIPELINE = [
  { icon: UploadCloud, label: "PDF Upload" },
  { icon: FileSearch, label: "OCR (PyMuPDF)" },
  { icon: Wand2, label: "Text Cleaning" },
  { icon: Scissors, label: "Smart Chunking" },
  { icon: Cpu, label: "FastEmbed · 384-D" },
  { icon: Database, label: "Qdrant Vector DB" },
  { icon: Search, label: "Semantic Search" },
  { icon: Bot, label: "Groq Llama 3.3" },
  { icon: CheckCircle2, label: "Grounded Answer" },
];

const BADGES = [
  "React", "FastAPI", "PostgreSQL", "FastEmbed", "Qdrant Cloud",
  "Groq Llama", "OCR", "JWT Authentication", "Role Based Access",
];

const FEATURES = [
  {
    icon: Bot,
    code: "MOD / AI-01",
    title: "AI Industrial Assistant",
    desc: "Workers ask plain-language questions and get answers generated by Groq Llama 3.3, grounded only in your uploaded documents.",
  },
  {
    icon: FileText,
    code: "MOD / DOC-02",
    title: "Semantic PDF Knowledge Base",
    desc: "Every manual is OCR'd, chunked, and embedded with FastEmbed into Qdrant — searchable by meaning, not just keywords.",
  },
  {
    icon: Users,
    code: "MOD / SEC-03",
    title: "Worker Approval & Management",
    desc: "Owners approve worker accounts, assign roles with JWT-based access, and monitor every question asked on the floor.",
  },
];

const STEPS = [
  { icon: UploadCloud, tag: "01", title: "Upload SOPs & manuals", desc: "Owners upload plant PDFs — SOPs, maintenance logs, safety sheets." },
  { icon: FileSearch, tag: "02", title: "OCR extracts text", desc: "PyMuPDF pulls clean text out of scanned pages and native PDFs alike." },
  { icon: Wand2, tag: "03", title: "Text is cleaned & chunked", desc: "Noise is stripped and content is split into intelligent, context-aware chunks." },
  { icon: Cpu, tag: "04", title: "FastEmbed generates embeddings", desc: "Each chunk becomes a 384-dimensional vector that captures its meaning." },
  { icon: Database, tag: "05", title: "Indexed in Qdrant", desc: "Vectors are stored in Qdrant Cloud for fast, scalable similarity search." },
  { icon: HardHat, tag: "06", title: "Worker asks a question", desc: "A plain-language question comes in from the floor, in real time." },
  { icon: Search, tag: "07", title: "Qdrant retrieves relevant chunks", desc: "Semantic search surfaces the passages closest in meaning to the question." },
  { icon: Bot, tag: "08", title: "Groq Llama generates the answer", desc: "Llama 3.3 answers using only the retrieved chunks — document-grounded, not guessed." },
  { icon: LayoutDashboard, tag: "09", title: "Owner monitors activity", desc: "Every query is logged, surfacing documentation gaps automatically." },
];

const GROUNDING = [
  { icon: Cpu, label: "384-D Vector Embeddings" },
  { icon: Search, label: "Semantic Search" },
  { icon: CheckCircle2, label: "Document-Grounded Responses" },
  { icon: Database, label: "Vector Retrieval" },
];

const STACK = ["React", "FastAPI", "PostgreSQL", "FastEmbed", "Qdrant Cloud", "Groq", "Render", "Netlify"];


function AmbientBackground() {
  const particles = [
    { top: "12%", left: "8%", d: "0s", c: "#F2B705" },
    { top: "22%", left: "88%", d: "1.2s", c: "#6FA8DC" },
    { top: "45%", left: "5%", d: "2.1s", c: "#6FA8DC" },
    { top: "60%", left: "92%", d: "0.6s", c: "#F2B705" },
    { top: "78%", left: "15%", d: "1.7s", c: "#6FA8DC" },
    { top: "85%", left: "70%", d: "2.6s", c: "#F2B705" },
  ];
  return (
    <>
      {/* blueprint grid */}
      <div
        className="pointer-events-none absolute inset-0 opacity-[0.06]"
        style={{
          backgroundImage:
            "linear-gradient(#6FA8DC 1px, transparent 1px), linear-gradient(90deg, #6FA8DC 1px, transparent 1px)",
          backgroundSize: "48px 48px",
        }}
      />
      {/* ambient glow */}
      <div className="pointer-events-none absolute -top-40 left-1/2 h-[520px] w-[900px] -translate-x-1/2 rounded-full bg-[#F2B705]/[0.08] blur-[130px]" />

      {/* faint circuit traces */}
      <svg className="pointer-events-none absolute inset-0 h-full w-full opacity-[0.08]" preserveAspectRatio="none">
        <path d="M0,120 H220 V260 H520" stroke="#6FA8DC" strokeWidth="1" fill="none" />
        <path d="M0,420 H160" stroke="#6FA8DC" strokeWidth="1" fill="none" className="circuit-pulse" />
        <path d="M100%,180 H80% V60" stroke="#F2B705" strokeWidth="1" fill="none" transform="translate(-1,0)" />
      </svg>

      {/* scan line */}
      <div className="pointer-events-none absolute inset-x-0 top-0 h-24 scan-line" />

      {/* floating particles */}
      {particles.map((p, i) => (
        <span
          key={i}
          className="pointer-events-none absolute h-1 w-1 rounded-full float-particle"
          style={{ top: p.top, left: p.left, background: p.c, animationDelay: p.d }}
        />
      ))}
    </>
  );
}

export default function LandingPage() {
  return (
    <div className="relative min-h-screen overflow-hidden bg-[#0A0D12] font-['Inter'] text-[#EDEFF2]">
      <AmbientBackground />

      {/* Navbar */}
      <nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between border-b border-white/[0.08] px-8 py-5">
        <div className="flex flex-col leading-none">
          <h1 className="font-['Oswald'] text-2xl font-bold tracking-wide text-[#F2B705]">IKIP</h1>
          <span className="mt-1 font-['JetBrains_Mono'] text-[10px] tracking-[0.2em] text-[#5C6472]">
            REV&nbsp;2.4&nbsp;·&nbsp;INDUSTRIAL&nbsp;OS
          </span>
        </div>
        <div className="flex items-center gap-7">
          <Link to="/login" className="group relative font-['JetBrains_Mono'] text-sm tracking-wide text-[#8B93A1] transition-colors hover:text-white">
            Login
            <span className="absolute -bottom-1 left-0 h-px w-0 bg-[#F2B705] transition-all duration-300 group-hover:w-full" />
          </Link>
          <Link
            to="/register"
            className="rounded-md bg-[#F2B705] px-5 py-2.5 font-['JetBrains_Mono'] text-sm font-semibold tracking-wide text-[#0A0D12] transition-all duration-300 hover:-translate-y-0.5 hover:brightness-110 hover:shadow-[0_0_24px_-4px_#F2B705]"
          >
            Register
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative z-10 mx-auto grid max-w-7xl grid-cols-1 items-center gap-16 px-8 py-24 md:grid-cols-[1.15fr_0.85fr] md:py-28">
        <div>
          <Reveal variant="up">
            <span className="inline-flex items-center gap-2 rounded-sm border border-[#F2B705]/40 bg-[#F2B705]/[0.06] px-4 py-1.5 font-['JetBrains_Mono'] text-xs tracking-[0.15em] text-[#F2B705]">
              <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#F2B705]" />
              RETRIEVAL-AUGMENTED INDUSTRIAL AI
            </span>
          </Reveal>

          <Reveal variant="up" delay={80}>
            <h1 className="mt-8 font-['Oswald'] text-5xl font-bold uppercase leading-[1.05] tracking-tight text-white md:text-6xl">
              Industrial Knowledge
              <br />
              <span className="text-[#6FA8DC]">Intelligence</span> Platform
            </h1>
          </Reveal>

          <Reveal variant="up" delay={140}>
            <p className="mt-6 max-w-xl text-lg leading-relaxed text-[#8B93A1]">
              Transform SOPs, maintenance manuals and safety documents into an
              intelligent, searchable knowledge base.
            </p>
            <p className="mt-4 max-w-xl text-sm leading-relaxed text-[#8B93A1]">
              Upload industrial PDFs once. Our AI extracts text, creates vector
              embeddings with FastEmbed, indexes them in Qdrant Cloud, and
              generates document-grounded answers using Groq Llama. Workers get
              accurate answers in seconds — owners manage the entire knowledge
              base from one dashboard.
            </p>
          </Reveal>

          <Reveal variant="up" delay={200}>
            <div className="mt-10 flex flex-wrap items-center gap-4">
              <Link
                to="/login"
                className="group flex items-center gap-2 rounded-md bg-[#F2B705] px-7 py-4 font-['JetBrains_Mono'] font-semibold tracking-wide text-[#0A0D12] transition-all duration-300 hover:-translate-y-0.5 hover:brightness-110 hover:shadow-[0_0_30px_-4px_#F2B705]"
              >
                Login
                <ArrowRight size={18} className="transition-transform duration-300 group-hover:translate-x-1" />
              </Link>
              <Link
                to="/register"
                className="rounded-md border border-white/[0.12] px-7 py-4 font-['JetBrains_Mono'] tracking-wide text-[#8B93A1] transition-all duration-300 hover:-translate-y-0.5 hover:border-[#6FA8DC]/50 hover:bg-[#6FA8DC]/[0.08] hover:text-white"
              >
                Create Worker Account
              </Link>
            </div>
          </Reveal>

          {/* Tech badges */}
          <Reveal variant="up" delay={260}>
            <div className="mt-10 flex flex-wrap gap-2.5">
              {BADGES.map((b, i) => (
                <span
                  key={b}
                  style={{ transitionDelay: `${260 + i * 40}ms` }}
                  className="rounded-full border border-white/[0.10] bg-white/[0.02] px-3.5 py-1.5 font-['JetBrains_Mono'] text-[11px] tracking-wide text-[#8B93A1] transition-all duration-300 hover:-translate-y-0.5 hover:border-[#F2B705]/50 hover:text-[#F2B705] hover:shadow-[0_0_16px_-4px_#F2B705]"
                >
                  {b}
                </span>
              ))}
            </div>
          </Reveal>
        </div>

        
        <Reveal variant="scale" delay={120}>
          <div className="relative rounded-xl border border-white/[0.08] bg-white/[0.02] p-6">
            <span className="absolute left-3 top-3 h-3 w-3 border-l border-t border-[#F2B705]/60" />
            <span className="absolute right-3 top-3 h-3 w-3 border-r border-t border-[#F2B705]/60" />
            <span className="absolute bottom-3 left-3 h-3 w-3 border-b border-l border-[#F2B705]/60" />
            <span className="absolute bottom-3 right-3 h-3 w-3 border-b border-r border-[#F2B705]/60" />

            <div className="mb-5 flex items-center justify-between font-['JetBrains_Mono'] text-[10px] tracking-[0.2em] text-[#5C6472]">
              <span>RAG&nbsp;PIPELINE</span>
              <span className="flex items-center gap-1 text-[#F2B705]">
                <span className="h-1.5 w-1.5 rounded-full bg-[#F2B705] animate-pulse" />
                LIVE
              </span>
            </div>

            <div className="relative ml-4 border-l border-dashed border-white/[0.15] pl-6">
              <span className="pipeline-dot absolute left-[-3px] top-0 h-1.5 w-1.5 rounded-full bg-[#F2B705] shadow-[0_0_8px_2px_#F2B70588]" />
              {PIPELINE.map(({ icon: Icon, label }, i) => (
                <div
                  key={label}
                  className="node-glow relative flex items-center gap-3 py-2.5"
                  style={{ animationDelay: `${i * 0.5}s` }}
                >
                  <span className="absolute left-[-31px] flex h-8 w-8 items-center justify-center rounded-full border border-[#6FA8DC]/40 bg-[#10141C]">
                    <Icon size={14} className="text-[#6FA8DC]" />
                  </span>
                  <span className="font-['JetBrains_Mono'] text-[11px] tracking-wide text-[#EDEFF2]">{label}</span>
                </div>
              ))}
            </div>
          </div>
        </Reveal>
      </section>

      {/* Ticker */}
      <div className="relative z-10 flex overflow-hidden border-y border-white/[0.08] bg-white/[0.02] py-3">
        <div className="flex shrink-0 animate-[scroll_26s_linear_infinite] gap-10 whitespace-nowrap font-['JetBrains_Mono'] text-xs tracking-[0.2em] text-[#5C6472]">
          {Array(2).fill(0).map((_, i) => (
            <span key={i} className="flex items-center gap-10">
              <span>OCR</span><span className="text-[#F2B705]">◆</span>
              <span>SMART&nbsp;CHUNKING</span><span className="text-[#F2B705]">◆</span>
              <span>384-D&nbsp;EMBEDDINGS</span><span className="text-[#F2B705]">◆</span>
              <span>QDRANT&nbsp;VECTOR&nbsp;DB</span><span className="text-[#F2B705]">◆</span>
              <span>GROQ&nbsp;LLAMA&nbsp;3.3</span><span className="text-[#F2B705]">◆</span>
              <span>SAFETY&nbsp;PROTOCOLS</span><span className="text-[#F2B705]">◆</span>
            </span>
          ))}
        </div>
      </div>

      {/* Feature nameplates */}
      <section className="relative z-10 mx-auto grid max-w-6xl gap-6 px-8 py-24 md:grid-cols-3">
        {FEATURES.map(({ icon: Icon, code, title, desc }, i) => (
          <Reveal key={code} variant="up" delay={i * 100}>
            <div className="group relative h-full rounded-xl border border-white/[0.08] bg-white/[0.02] p-8 transition-all duration-300 hover:-translate-y-1.5 hover:border-[#F2B705]/50 hover:bg-white/[0.04] hover:shadow-[0_0_35px_-10px_#F2B705]">
              <span className="absolute left-3 top-3 h-3 w-3 border-l border-t border-white/[0.10] transition-colors duration-300 group-hover:border-[#F2B705]/70" />
              <span className="absolute right-3 top-3 h-3 w-3 border-r border-t border-white/[0.10] transition-colors duration-300 group-hover:border-[#F2B705]/70" />
              <span className="absolute bottom-3 left-3 h-3 w-3 border-b border-l border-white/[0.10] transition-colors duration-300 group-hover:border-[#F2B705]/70" />
              <span className="absolute bottom-3 right-3 h-3 w-3 border-b border-r border-white/[0.10] transition-colors duration-300 group-hover:border-[#F2B705]/70" />
              <div className="flex items-center justify-between">
                <span className="font-['JetBrains_Mono'] text-[10px] tracking-widest text-[#5C6472]">{code}</span>
                <span className="h-1.5 w-1.5 rounded-full bg-[#3DDC84]/70 transition group-hover:bg-[#F2B705]" />
              </div>
              <Icon className="mt-5 text-[#6FA8DC] transition-all duration-300 group-hover:scale-110 group-hover:text-[#F2B705]" size={28} />
              <h2 className="mt-4 font-['Oswald'] text-xl font-semibold uppercase tracking-wide text-white">{title}</h2>
              <p className="mt-3 text-sm leading-relaxed text-[#8B93A1]">{desc}</p>
            </div>
          </Reveal>
        ))}
      </section>

      {/* Full process — the actual AI workflow */}
      <section className="relative z-10 mx-auto max-w-4xl px-8 py-24">
        <Reveal variant="left">
          <span className="font-['JetBrains_Mono'] text-xs tracking-[0.2em] text-[#F2B705]">RAG&nbsp;WORKFLOW</span>
          <h2 className="mt-3 font-['Oswald'] text-3xl font-bold uppercase tracking-tight text-white md:text-4xl">
            From PDF to grounded answer
          </h2>
        </Reveal>

        <div className="relative mt-14 ml-5 border-l border-dashed border-white/[0.15]">
          <span className="absolute left-[-3px] top-0 h-1.5 w-1.5 animate-[travel_9s_linear_infinite] rounded-full bg-[#F2B705] shadow-[0_0_8px_2px_#F2B70588]" />
          {STEPS.map(({ icon: Icon, tag, title, desc }, i) => (
            <Reveal key={tag} variant={i % 2 === 0 ? "left" : "right"} className="relative pb-14 pl-10 last:pb-0">
              <span className="absolute left-[-25px] top-0 flex h-11 w-11 items-center justify-center rounded-full border border-[#F2B705]/40 bg-[#10141C]">
                <Icon size={18} className="text-[#F2B705]" />
              </span>
              <span className="font-['JetBrains_Mono'] text-[11px] tracking-[0.2em] text-[#5C6472]">STEP {tag}</span>
              <h3 className="mt-1 font-['Oswald'] text-xl font-semibold uppercase tracking-wide text-white">{title}</h3>
              <p className="mt-2 max-w-lg text-sm leading-relaxed text-[#8B93A1]">{desc}</p>
            </Reveal>
          ))}
        </div>
      </section>

      <section className="relative z-10 mx-auto max-w-6xl px-8 py-24">
        <Reveal variant="scale">
          <div className="relative overflow-hidden rounded-xl border border-white/[0.08] bg-white/[0.02] p-10">
            <div className="pointer-events-none absolute -right-16 -top-16 h-64 w-64 rounded-full bg-[#F2B705]/[0.10] blur-[100px]" />

            <div className="relative flex items-center gap-4">
              <span className="flex h-14 w-14 items-center justify-center rounded-lg border border-[#F2B705]/50 bg-[#F2B705]/[0.08]">
                <ShieldCheck size={26} className="text-[#F2B705]" />
              </span>
              <div>
                <span className="font-['JetBrains_Mono'] text-xs tracking-[0.2em] text-[#F2B705]">BUILT ON REAL RETRIEVAL</span>
                <h2 className="mt-1 font-['Oswald'] text-2xl font-bold uppercase tracking-tight text-white md:text-3xl">
                  Not a generic chatbot
                </h2>
              </div>
            </div>

            <div className="relative mt-10 grid grid-cols-1 gap-4 border-t border-white/[0.08] pt-8 sm:grid-cols-2 lg:grid-cols-4">
              {GROUNDING.map(({ icon: Icon, label }, i) => (
                <Reveal key={label} variant="scale" delay={i * 90}>
                  <div className="flex h-full flex-col items-start gap-3 rounded-lg border border-white/[0.08] bg-black/20 p-5 transition-all duration-300 hover:border-[#6FA8DC]/40">
                    <Icon size={20} className="text-[#6FA8DC]" />
                    <span className="font-['JetBrains_Mono'] text-xs leading-snug tracking-wide text-[#EDEFF2]">{label}</span>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </Reveal>
      </section>

      {/* Powered by — tech stack */}
      <section className="relative z-10 mx-auto max-w-6xl px-8 py-24">
        <Reveal variant="up">
          <span className="font-['JetBrains_Mono'] text-xs tracking-[0.2em] text-[#F2B705]">INFRASTRUCTURE</span>
          <h2 className="mt-3 font-['Oswald'] text-3xl font-bold uppercase tracking-tight text-white md:text-4xl">
            Powered by
          </h2>
        </Reveal>

        <div className="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-4">
          {STACK.map((name, i) => (
            <Reveal key={name} variant="scale" delay={i * 60}>
              <div className="group flex items-center justify-center rounded-lg border border-white/[0.08] bg-white/[0.02] px-4 py-6 text-center transition-all duration-300 hover:-translate-y-1 hover:border-[#F2B705]/50 hover:shadow-[0_0_24px_-8px_#F2B705]">
                <span className="font-['JetBrains_Mono'] text-sm tracking-wide text-[#8B93A1] transition-colors group-hover:text-[#F2B705]">
                  {name}
                </span>
              </div>
            </Reveal>
          ))}
        </div>
      </section>

      {/* Final CTA */}
      <section className="relative z-10 mx-auto max-w-6xl px-8 pb-28">
        <Reveal variant="scale">
          <div className="relative rounded-xl border border-[#F2B705]/30 bg-gradient-to-b from-[#F2B705]/[0.06] to-transparent px-8 py-16 text-center">
            <span className="absolute left-3 top-3 h-3 w-3 border-l border-t border-[#F2B705]/60" />
            <span className="absolute right-3 top-3 h-3 w-3 border-r border-t border-[#F2B705]/60" />
            <span className="absolute bottom-3 left-3 h-3 w-3 border-b border-l border-[#F2B705]/60" />
            <span className="absolute bottom-3 right-3 h-3 w-3 border-b border-r border-[#F2B705]/60" />

            <h2 className="font-['Oswald'] text-3xl font-bold uppercase tracking-tight text-white md:text-4xl">
              Put your SOPs to work
            </h2>
            <p className="mx-auto mt-4 max-w-md text-[#8B93A1]">
              Set up your knowledge base in minutes and give every worker a direct, document-grounded line to the answer.
            </p>
            <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
              <Link
                to="/register"
                className="group flex items-center gap-2 rounded-md bg-[#F2B705] px-7 py-4 font-['JetBrains_Mono'] font-semibold tracking-wide text-[#0A0D12] transition-all duration-300 hover:-translate-y-0.5 hover:brightness-110 hover:shadow-[0_0_30px_-4px_#F2B705]"
              >
                Get started
                <ArrowRight size={18} className="transition-transform duration-300 group-hover:translate-x-1" />
              </Link>
              <Link
                to="/login"
                className="rounded-md border border-white/[0.12] px-7 py-4 font-['JetBrains_Mono'] tracking-wide text-[#8B93A1] transition-all duration-300 hover:-translate-y-0.5 hover:border-[#6FA8DC]/50 hover:bg-[#6FA8DC]/[0.08] hover:text-white"
              >
                Login
              </Link>
            </div>
          </div>
        </Reveal>
      </section>

      {/* Footer */}
      <footer className="relative z-10 mx-auto flex max-w-7xl flex-col items-center justify-between gap-3 border-t border-white/[0.08] px-8 py-6 font-['JetBrains_Mono'] text-[10px] tracking-[0.15em] text-[#5C6472] sm:flex-row">
        <span>IKIP&nbsp;INDUSTRIAL&nbsp;OS&nbsp;© 2026</span>
        <span className="flex items-center gap-2">
          <KeyRound size={12} className="text-[#5C6472]" />
          JWT&nbsp;SECURED&nbsp;·&nbsp;ROLE-BASED&nbsp;ACCESS
        </span>
        <span className="flex items-center gap-2">
          <span className="h-1.5 w-1.5 rounded-full bg-[#3DDC84]" />
          STATUS:&nbsp;OPERATIONAL
        </span>
      </footer>

      <style>{`
        @keyframes scroll { from { transform: translateX(0); } to { transform: translateX(-50%); } }
        @keyframes travel { 0% { top: 0%; opacity: 0; } 5% { opacity: 1; } 95% { opacity: 1; } 100% { top: 100%; opacity: 0; } }
        .pipeline-dot { animation: travel 4.5s linear infinite; }

        @keyframes nodeGlow {
          0%, 100% { box-shadow: none; }
          8% { box-shadow: 0 0 0 3px rgba(242,183,5,0.15); }
          16% { box-shadow: none; }
        }
        .node-glow { animation: nodeGlow 4.5s linear infinite; }

        @keyframes floatParticle {
          0%, 100% { transform: translateY(0); opacity: 0.5; }
          50% { transform: translateY(-14px); opacity: 1; }
        }
        .float-particle { animation: floatParticle 6s ease-in-out infinite; }

        @keyframes circuitPulse {
          0%, 100% { stroke-opacity: 0.15; }
          50% { stroke-opacity: 0.6; }
        }
        .circuit-pulse { animation: circuitPulse 4s ease-in-out infinite; }

        @keyframes scanMove {
          0% { transform: translateY(-10%); opacity: 0; }
          10% { opacity: 0.5; }
          90% { opacity: 0.5; }
          100% { transform: translateY(110vh); opacity: 0; }
        }
        .scan-line {
          background: linear-gradient(to bottom, transparent, rgba(111,168,220,0.06), transparent);
          animation: scanMove 10s linear infinite;
        }

        @media (prefers-reduced-motion: reduce) {
          .pipeline-dot, .node-glow, .float-particle, .circuit-pulse, .scan-line {
            animation: none !important;
          }
        }
      `}</style>
    </div>
  );
}